project_id = "qqceibvalkoytafynwoc"

[functions]
  [functions.asper-intelligence]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.concierge-tip]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-transactional-email]
    verify_jwt = false
  [functions.sync-shopify-catalog]
    verify_jwt = false
  [functions.ingest-catalog]
    verify_jwt = false
  [functions.beauty-assistant]
    verify_jwt = false
