#!/bin/bash

# Shopify Webhooks - Quick Setup Script
# This script helps you set up Shopify webhooks in your store

set -e

echo "🔗 Shopify Webhooks Setup Helper"
echo "=================================="
echo ""

# Configuration
WEBHOOK_URL="https://vhgwvfedgfmcixhdyttt.supabase.co/functions/v1/shopify-webhooks"
SHOPIFY_STORE="lovable-project-milns.myshopify.com"
WEBHOOK_SECRET="40e33b99d11b92862feca7474996a40f1c67b7f4cfa357d0ee70c5b26d01c48f"

echo "📋 Your Shopify Webhook Configuration:"
echo ""
echo "Store: https://$SHOPIFY_STORE/admin"
echo "Webhook URL: $WEBHOOK_URL"
echo "API Version: 2025-07"
echo ""
echo "---"
echo ""

echo "📝 Webhooks to Create (in Shopify Admin → Settings → Notifications):"
echo ""
echo "1. Product creation"
echo "   Event: Product creation"
echo "   Format: JSON"
echo "   URL: $WEBHOOK_URL"
echo ""
echo "2. Product update"
echo "   Event: Product update"
echo "   Format: JSON"
echo "   URL: $WEBHOOK_URL"
echo ""
echo "3. Product deletion"
echo "   Event: Product deletion"
echo "   Format: JSON"
echo "   URL: $WEBHOOK_URL"
echo ""
echo "4. Order creation"
echo "   Event: Order creation"
echo "   Format: JSON"
echo "   URL: $WEBHOOK_URL"
echo ""
echo "5. Order payment"
echo "   Event: Order payment"
echo "   Format: JSON"
echo "   URL: $WEBHOOK_URL"
echo ""
echo "6. Inventory levels update"
echo "   Event: Inventory levels update"
echo "   Format: JSON"
echo "   URL: $WEBHOOK_URL"
echo ""
echo "---"
echo ""

echo "🔐 Webhook Secret (for verification):"
echo "$WEBHOOK_SECRET"
echo ""
echo "(This is already configured in your Supabase secrets)"
echo ""
echo "---"
echo ""

echo "🧪 Testing Your Webhooks:"
echo ""
echo "After creating webhooks in Shopify:"
echo "1. Click on each webhook in Shopify Admin"
echo "2. Click 'Send test notification'"
echo "3. Check if notification succeeds"
echo ""
echo "Monitor webhook activity:"
echo "  npx supabase functions logs shopify-webhooks --project-ref vhgwvfedgfmcixhdyttt -f"
echo ""
echo "---"
echo ""

echo "✅ Next Steps:"
echo ""
echo "1. Open: https://$SHOPIFY_STORE/admin/settings/notifications"
echo "2. Scroll to 'Webhooks' section"
echo "3. Create the 6 webhooks listed above"
echo "4. Test each webhook"
echo "5. Monitor logs to verify they work"
echo ""
echo "📚 Full guide: SHOPIFY_WEBHOOKS_SETUP.md"
echo ""
echo "🎉 Once webhooks are active, your Telegram bots will receive:"
echo "   • Real-time product updates"
echo "   • New order notifications"
echo "   • Low stock alerts"
echo "   • Inventory changes"
echo ""
