// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const FALLBACK_SUPABASE_URL = "https://vhgwvfedgfmcixhdyttt.supabase.co";
const FALLBACK_SUPABASE_PUBLISHABLE_KEY = "public-anon-key-not-configured";

const ENV_SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL ?? "").trim();
const ENV_SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "").trim();

const SUPABASE_URL = ENV_SUPABASE_URL || FALLBACK_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = ENV_SUPABASE_PUBLISHABLE_KEY || FALLBACK_SUPABASE_PUBLISHABLE_KEY;

if (!ENV_SUPABASE_URL) {
  console.error(
    "[Asper] VITE_SUPABASE_URL is not set. Falling back to the project default URL to avoid startup crashes. Add it to your .env file (see .env.example).",
  );
}
if (!ENV_SUPABASE_PUBLISHABLE_KEY) {
  console.error(
    "[Asper] VITE_SUPABASE_PUBLISHABLE_KEY is not set. Falling back to the project publishable key to avoid startup crashes. Add it to your .env file (see .env.example).",
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  },
);
