name: Authzed Test Server

on:
  workflow_dispatch:

permissions: {}

jobs:
  run-authzed-test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Run Authzed Test Server
        uses: authzed/action-testserver@v3
        with:
          version: latest
          
